muon-spectroscopy-computational-project/muspinsim

muspinsim/input/input.py, muspinsim/input/keyword.py, muspinsim/input/larkeval.py, muspinsim/input/variables.py, muspinsim/simconfig.py, test/test_constants.py, test/test_input.py, test/test_lark.py
Some misc improvements to tests that I collected into a PR
mostly making sure error messages we expect to see in tests are the correct ones
Improvements to error messages when `validate_values()` method fails for MuSpinKeyword objects 
Added test case for `KWFittingVariables` where variable name clashes with constant
=> Testing Improvements

muspinsim/__main__.py, muspinsim/fitting.py, test/test_args.py
simple change to add command line arguments to specify where to save output files and log files etc
```
muspinsim --help
usage: __main__.py [-h] [-o OUT_DIR] [-l LOG_PATH] [-f FITREPORT_PATH]
input_file
Muspinsim - A program designed to carry out spin dynamics calculations for
muon science experiments
positional arguments:
input_file            filepath to muspinsim specially formatted text file
specifying simulation input parameters.
options:
-h, --help            show this help message and exit
-o OUT_DIR, --out-dir OUT_DIR
folder to store the output .dat files
-l LOG_PATH, --log-path LOG_PATH
filepath to store simulation logs
-f FITREPORT_PATH, --fitreport-path FITREPORT_PATH
filepath to store fit report if fitting parameters
given
```
=> Add more command line arguments

docs/docs/hamiltonian.md, docs/docs/theory_1.md, docs/docs/theory_2.md
Adds a section to the documentation describing the speedup for T->inf/B=0 cases as implemented in #22. I have pretty much copied Johnny's explanation from https://github.com/muon-spectroscopy-computational-project/Developer-notes/blob/main/muspinsim/speedup_suggestions.md.
Also noticed the docs mentioned implementing faster approximate methods of time evolution in the future so modified it to mention celio's.
=> Add documentation for the faster method

docs/docs/examples.md, muspinsim/experiment.py, setup.py
Stops repeated creation of SpinSystem instances that are never used, especially when fitting. Also adds ase to the dependencies in setup.py as it was missing before.
Also makes a minor change to the wording of the ALC experiment docs to match https://github.com/muon-spectroscopy-computational-project/training-material/pull/4#discussion_r1044524599
Closes #30, Closes #18.
=> Fix repeated system creation and add ase to dependencies

docs/docs/input.md, muspinsim/experiment.py, muspinsim/input/keyword.py, muspinsim/simconfig.py, test/test_config.py, test/test_experiment.py, test/test_spinsys.py
Allows an intrinsic magnetic field to be defined using an `intrinsic_field` parameter. This is unaffected by rotations such as when angular averaging as suggested in #25. This PR also adds it to the docs.
Closes #25
=> Allow intrinsic magnetic fields

docs/docs/examples.md
As part of the discussion on muon-spectroscopy-computational-project/training-material/pull/4 (which uses material from the MSS docs), resolved that TeX formatting should not be used for single values with associated units, and that this should be adopted consistently across documentation.
=> Remove LaTeX formatting from single value/units

README.md, docs/docs/index.md, docs/docs/input.md, docs/docs/installation.md, docs/docs/theory_1.md, docs/mkdocs.yml
- Adds an installation page to the docs including information on compiling from source
- Enabled admonition and uses to make warnings and notes clearer on the examples page e.g.
Notes
- The environment variable MUSPINSIM_OPENMP is added in #35 
- We recently added install docs here https://muon-spectroscopy-computational-project.github.io/tutorial-folder/installing-muspinsim, but this does not include info on compilation. I think we should either remove it and link to these new ones like the tutorials, or otherwise treat them separately as a simpler set of instructions without the compilation since the compilation info should be dependent on the muspinsim version
Closes #27
=> Add compilation docs

.github/workflows/build.yml, .github/workflows/test.yml, CITATION.cff, muspinsim/version.py
Update ready for release
Actual doi for 2.0.0 will need to be force updated later as per step 5 in https://github.com/muon-spectroscopy-computational-project/Developer-notes/blob/main/package-maintenance.md.
MacOS runner images were also updated yesterday and have replaced llvm@14 with 15 but even after updating fails for python 3.10 so updated to pin to macOS-11 as macOS-12 appears unstable at least until proper release on the 1st of March.
=> Update version to 2.0.0 and update CITATION.cff #38

.github/workflows/build.yml, CITATION.cff, MANIFEST.in, muspinsim/version.py
Turns out header files are ignored when building the source distribution, this creates a minor release 2.0.1 fixing this and adds a test to the sdist build to hopefully avoid any similar issues in the future.
=> Fix missing files from source distribution

CITATION.cff, muspinsim/__main__.py, muspinsim/mpi.py, muspinsim/tests/test_args.py, muspinsim/version.py
Fixes issue when using mpirun as there was an assignment outside of the main thread requiring a variable only assigned within it. Also fixes some linting warnings I came across and adds more unit tests to cover the errors as they were missing before.
Closes #42
=> Fix mpirun errors #42

muspinsim/experiment.py, muspinsim/spinsys.py, muspinsim/tests/test_experiment.py
During testing 7+ 7/2 spins I discovered the memory usage was higher than I expected. Turns out muspinsim was still pre-calculating large matrices that were never used in Celio's method. I have now modified it to stop this, reducing memory usage by a further factor of 8 in this case.
Closes #48
=> Further memory reduction for Celio's #48

muspinsim/__main__.py, muspinsim/celio.py, muspinsim/constants.py, muspinsim/experiment.py, muspinsim/fitting.py, muspinsim/hamiltonian.py, muspinsim/input/input.py, muspinsim/input/keyword.py, muspinsim/input/larkeval.py, muspinsim/input/variables.py, muspinsim/lindbladian.py, muspinsim/mpi.py, muspinsim/simconfig.py, muspinsim/spinop.py, muspinsim/spinsys.py, muspinsim/tests/test_input.py, muspinsim/tests/test_mpi.py, muspinsim/utils.py, muspinsim/validation.py
Fixes various issues given by vscode's pylint plugin e.g.
C0116:missing-function-docstring
C0209:consider-using-f-string
C0103:invalid-name
W0102:dangerous-default-value
R0205:useless-object-inheritance
C0325:superfluous-parens
R1701:consider-merging-isinstance
C0411:wrong-import-order
R1705:no-else-return
R0401:cyclic-import
Many still remain, but its an improvement and some of these above can cause unexpected behaviour if misused.
- Ended up leaving in various str(exc)’s despite using `raise … from …` as it has the following effect (as a result also reverted the one from #43):
instead of
=> Fix various pylint errors and warnings

muspinsim/input/gipaw.py, muspinsim/input/structure.py, muspinsim/input/structure/structure.py, muspinsim/tests/test_generator.py, muspinsim/tests/test_gipaw.py, muspinsim/tests/test_structure.py, muspinsim/tools/generator.py, setup.py
Adds methods to load in a structure file via `ase` (e.g. .cell) and use it to determine the closest atoms to the muon. There is then also a function to create input file text like I used for V3Si.
Still currently leaning towards keeping this out of the config file itself, due to its kind of sketchy nature as it would make it easy to make amendments to what it outputs in the case it doesn't do quite what you might expect. In this case I would think for galaxy we can use it as a library and hide the spin/interaction options when used. Then if the user wants to make modifications they can modify the resulting text file.
Current usage:
```
muspinsim-gen --help
muspinsim-gen V3Si_SC.cell 6 --dipolar --quadrupolar ./efg_nospin.out --ignore_symbol Si
```
- ase logs warnings that castep isn't …
=> Add cell file tool #50

muspinsim/input/structure.py, muspinsim/tests/test_generator.py, muspinsim/tests/test_structure.py, muspinsim/tools/generator.py
Modifies behaviour of muspinsim-gen so that it can take a magres file with EFG tensors defined. Then `muspinsim-gen` with `--quadrupolar` will attempt to use these tensors. `--quadrupolar GIPAW_OUTPUT_FILEPATH` will instead load them from the gipaw output file as before.
I also clarified with Leandro - the GIPAW file output was the result of using Quantum ESPRESSO, whereas the magres file came from CASTEP and we would like to be able to use either here.
=> Add magres file support for obtaining EFG tensors

muspinsim/input/structure.py, muspinsim/tests/test_generator.py, muspinsim/tests/test_structure.py, muspinsim/tools/generator.py
- Modifies default value of isotope in the atoms loaded in the structure file as None instead of 1 - I think this makes more sense and it means the isotope parameters can be obtained without needing any extra logic
- Adds a parameter --include_interatomic for adding interactions between the nuclei themselves
- Restructures the code slightly so I can insert Johnny's method for moving the nuclei prior to producing the output file
For context I have also committed my use of these changes to apply Johnny's method for moving the nn-F's here: https://github.com/muon-spectroscopy-computational-project/Developer-notes/blob/main/muspinsim/johnnys_method.py
I could add this to the PR as well if it seems appropriate but am unsure myself.
=> Additional generator changes

muspinsim/input/gipaw.py, muspinsim/input/structure.py, muspinsim/tests/test_gipaw.py
Fixes two things
- muspinsim-gen without any ignored_symbol resulted in a log "Ignoring the symbols" (condition previously only checked for None, but in this case it was an empty list)
- Specifying an invalid gipaw output file for --quadrupolar resulted in an infinite loop as `readline` just infinitely returns empty lines
=> Fix some bugs with muspinsim-gen

muspinsim/input/input.py, muspinsim/simconfig.py, muspinsim/tests/test_input.py
Adds an error as discussed on https://github.com/muon-spectroscopy-computational-project/muon-galaxy-tools/pull/132, resulting in errors of the form
when defining an input file with
```
hyperfine 2
580 5   10
5   580 9
10  9   580
hyperfine 2
150 3   4
3   150 5
4   5   150
```
Also modifies two other errors for invalid indents and invalid formatting to be of type MuSpinInputError instead of RuntimeError.
Closes #71
=> Add error multiple definitions of the same block #71

muspinsim/experiment.py
While checking things for #74, I discovered when T_inf_speedup is true in experiment.py, and regular non averaged Celio's method is being used, we would still try and use the faster method for Celio's passing a nonsensical value as the number of averages. This ensures it doesn't happen. I tried adding tests for this with mocks, unfortunately it interferes with isinstance in a way that I think it would diminish their value.
Since this is a bigger issue I will rename the branch and release a v2.2.1 for this one.
=> Fix celios using wrong method when T_inf_speedup is True

docs/docs/input.md, muspinsim/__main__.py, muspinsim/celio.py, muspinsim/experiment.py, muspinsim/fitting.py, muspinsim/input/input.py, muspinsim/input/keyword.py, muspinsim/simconfig.py, muspinsim/tests/test_celio.py, muspinsim/tests/test_config.py, muspinsim/tests/test_experiment.py, muspinsim/tests/test_fitting.py, muspinsim/tests/test_input.py, muspinsim/tests/test_validation.py, muspinsim/validation.py
Adds a parameter `results_function` that can take all the usual constants, variables and functions available to the input file and additionally two extra 'x' and 'y' representing the output of muspinsim's simulation and runs it before outputting the results. This allows fitting on functions that modify the data e.g.
```
results_function
A*y+B
```
For a linear fit, offsetting the y values and scaling them.
This also detects when fitting parameters are present in any sections of the input other than this function, and in the case they are only used in `results_function` the FittingRunner will cache the results and only run the simulation once, but repeatedly fit with this function so that it can run significantly faster for large systems.
- Also adds `least-squares` as an additional fitting …
=> Add 'results_function' parameter for improving fitting capabilities #77

muspinsim/celio.py, muspinsim/experiment.py, muspinsim/hamiltonian.py, muspinsim/lindbladian.py, muspinsim/spinop.py, muspinsim/tests/test_celio.py, muspinsim/tests/test_hamiltonian.py, muspinsim/tests/test_lindbladian.py, muspinsim/tests/test_spinop.py, muspinsim/tests/test_validation.py, muspinsim/validation.py
Changes I made when looking into speeding up the sparse matrix usage. May be overridden in the future by removing sparse matrices altogether.
Using
```
name
Test
spins
e mu H
hyperfine 2
580 5   10
5   580 9
10  9   580
hyperfine 3
150 3   4
3   150 5
4   5   150
orientation
zcw(20)
field
range(1.8, 2.6, 100)
experiment
alc
```
as a baseline, v1.2.0 takes ~ 5 seconds.
- Stopped converting eigenvectors to a csr_matrix (this was always 100% dense in my testing)
This increased the performance of from ~29 seconds down to ~24
- Stopped generating Hz using sparse matrices in experiment.py's rho0 computation as this was made to be dense immediately after again - further reduction down to ~20 seconds
Checking against a largish system using ~480Mb (without celios) suggests the memory usage change …
=> Some sparse matrix usage improvements

CITATION.cff, docs/docs/input.md, muspinsim/fitting.py, muspinsim/simconfig.py, muspinsim/tests/test_config.py, muspinsim/tests/test_fitting.py, muspinsim/version.py
- Fixes an issue found while attempting to fit for an ALC experiment. It turned out the overriding behaviour of the x values for any fitting_data caused the fitting to fail as the magnetic field values were not converted to 3D vectors prior to rotating them.
- Also least-squares should really have been using an array of residuals, which is different to the minimise function which takes a single float value as input. This PR also fixes that.
- I also noticed curve_fit uses the 'lm' method of least-squares when the problem is unconstrained. This method is much faster and has less weirdness than the 'trf' method that supports constrained systems, so I also automatically switch between the two in this PR and updated the docs to reflect this.
- Finally single_simulation in fitting added with …
=> Fix ALC fitting #81

.coveragerc, .github/workflows/test.yml, README.md, requirements-dev.txt
Implements codecov for our GHA workflows, in the same manner as PyMuonSuite.
Also fixes the failing GHA for macOS OMP tests, by writing the libomp path to `$GITHUB_ENV`. This is currently causing failures on all branches/PRs.
=> Fix macOS OMP tests action and implement codecov

muspinsim/experiment.py, muspinsim/input/keyword.py, muspinsim/tests/test_experiment.py
To prevent errors when using file ranges, have refactored and overridden the code that attempts to reshape evaluated lark expressions only for `KWResultsFunction` (behviour elsewhere should be unchanged).
Added test to prevent future regression.
Closes #86
=> Do not reshape results_function evaluations #86

docs/docs/input.md, muspinsim/__main__.py, muspinsim/experiment.py, muspinsim/fitting.py, muspinsim/input/input.py, muspinsim/simconfig.py, muspinsim/tests/test_fitting.py
Adds handling for `x_axis` and `x_axis_values` for fitting experiments. The WARNING for overwriting values has been downgraded to INFO, and will only be printed when the x_axis is set by the user (this checks the value for `x_axis` and also if the default value of time is altered without explicitly changing `x_axis`). If no values given, we use the experimental data for the final evaluation of the function, and saving the .dat file.
If however the user specifies values, then these will be used only for the final .dat evaluation.
Considered interpolation/overlapping of ranges provided by the user, but decided that this was not the right approach as the experimental data contains all our information, and we will either be upscaling (implying a precision we do not possess) or downscaling …
=> Overwrite x_axis only during fitting #77
